"""Add user code to sessions

Revision ID: e86fd646a8db
Revises: 1b5bfa8b32a7
Create Date: 2026-08-22 15:49:18.388166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86fd646a8db'
down_revision: Union[str, Sequence[str], None] = '1b5bfa8b32a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('user_code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'user_code')
    # ### end Alembic commands ###
